import { ProxyItem } from "../documents/proxy-item.mjs"

const initData = async (slugs, type, transformFn) => {
    const folder = await Folder.create({ name: type, type: "Item", parent: null });
    const documents = slugs.map(slug => ({
        type: type,
        name: slug,
        folder: folder.id,
        system: {
            slug,
        },
    }));

    await ProxyItem.createDocuments(transformFn ? documents.map(transformFn) : documents);
}

const MANEUVERS = [
    "aim_long",
    "aim_short",
    "befriend",
    "blend_in",
    "block",
    "burst_long_range",
    "burst_short_range",
    "camouflage",
    "castigate_presence",
    "castigate_wits",
    "chase_escape",
    "chase_escape_piloting",
    "climb_dexterity",
    "climb_force",
    "command",
    "command_animal",
    "conceal",
    "concentrate",
    "confuse",
    "convince",
    "counterstrike",
    "create_art",
    "dabble",
    "daunt_presence",
    "daunt_strength",
    "debunk_empathy",
    "debunk_knavery",
    "deceive",
    "design_security",
    "detect",
    "detect_interface",
    "detect_lie",
    "disarm",
    "distract",
    "dodge_dexterity",
    "dodge_intuition",
    "empty_clip_long_range",
    "empty_clip_short_range",
    "encourage",
    "enter_memory_palace",
    "entreat",
    "evade",
    "evade",
    "evaluate_artwork",
    "evaluate_artwork_detect_fake",
    "exhort_charm",
    "exhort_impress",
    "find_book",
    "fish",
    "forge_artwork_dexterity",
    "forge_artwork_perception",
    "frolic",
    "grapple",
    "gunstorm_long_range",
    "gunstorm_short_range",
    "hack",
    "hack_and_slash",
    "haggle_charm",
    "haggle_knavery",
    "hold_breath",
    "humiliate",
    "hunt",
    "identify",
    "identify_animal",
    "identify_substance",
    "idle",
    "impersonate",
    "impersonate_alien",
    "invent",
    "jam",
    "jury_rig",
    "knockdown",
    "meditate",
    "mesmerize",
    "minister",
    "muse_arts",
    "muse_focus",
    "operate",
    "parry",
    "pick_lock",
    "pick_pocket",
    "program",
    "rally",
    "ram",
    "ram_piloting",
    "ready_focus",
    "ready_vigor",
    "rebuff",
    "refine",
    "rehabilitate",
    "remember",
    "repair",
    "repair_piloting",
    "research",
    "ride",
    "riposte",
    "rouse",
    "scope",
    "search",
    "shake_it_off_body",
    "shake_it_off_mind",
    "shake_it_off_spirit",
    "shoot_gun_long",
    "shoot_gun_short",
    "skulk",
    "snapshot",
    "snapshot",
    "spot",
    "spread",
    "strike",
    "stunt_piloting",
    "three_round_burst_long_range",
    "three_round_burst_short_range",
    "throw_long",
    "throw_short",
    "tinker_crafts",
    "tinker_tech_redemption",
    "train_beast",
    "traipse",
    "trap",
    "treat_wounds",
    "upgrade",
    "weapon_strike",
    "wow",
];

export const initManeuvers = async () => {
    await initData(MANEUVERS, "maneuver");
};
