import { ProxyItem } from "../documents/proxy-item.mjs"

const initData = async (slugs, type, transformFn) => {
    const folder = await Folder.create({ name: type, type: "Item", parent: null });
    const documents = slugs.map(slug => ({
        type: type,
        name: slug,
        folder: folder.id,
        system: {
            slug,
        },
    }));

    await ProxyItem.createDocuments(transformFn ? documents.map(transformFn) : documents);
}

const CAPABILITIES = [
    "archery",
    "architecture",
    "military_weapons",
    "artifact_weapon",
    "combat_armor",
    "war_armor",
    "oratory",
    "artillery",
    "aircraft",
    "handheld_shield",
    "beast_lore_barbarian_worlds",
    "beast_lore_known_worlds",
    "beast_lore",
    "gunnery",
    "energy_guns",
    "artifact_gun",
    "slug_guns",
    "cartography",
    "song",
    "carpentry",
    "surgery_lore",
    "court_customs",
    "cathedral_customs",
    "commons_customs",
    "cooking",
    "dance",
    "demolitions",
    "faction_lore",
    "blacksmithing",
    "history_lore",
    "imagery",
    "musical_instruments",
    "ai",
    "jewelry",
    "magic_lantern",
    "read_language_latin",
    "read_language",
    "read_speak_urthish",
    "think_machines",
    "disease_lore",
    "masonry",
    "streetwise",
    "planet_lore_homeworld",
    "beastback",
    "music",
    "occult_lore",
    "shipboard_operations",
    "speak_language_latin",
    "speak_language",
    "planet_lore",
    "poison_lore",
    "pottery",
    "poetry",
    "religion_lore",
    "jumpweb_lore_barbarian_worlds",
    "jumpweb_lore_known_worlds",
    "jumpweb_lore",
    "applied_science",
    "life_science",
    "physical_science",
    "sculpting",
    "locksmithing",
    "warfare_lore",
    "tailoring",
    "tl5",
    "tl6",
    "tl7",
    "tl8",
    "weird_tech",
    "terraforming",
    "theatre",
    "weaving",
    "torture_lore",
    "magic",
    "leatherworking",
    "watercraft",
    "spacecraft",
    "warcraft",
    "landcraft",
    "beastcraft",
    "xeno_lore",
    "writing",
];

export const initCapabilities = async () => {
    await initData(CAPABILITIES, "capability");
}
